# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu-usuario/argocd-nginx-example.git  # Cambia esto a tu repo
    targetRevision: HEAD
    path: chart  # Indica que los manifiestos están en el directorio 'chart'
  destination:
    server: https://kubernetes.default.svc  # Apunta al clúster local de Kubernetes
    namespace: nginx-example  # Namespace donde se desplegará la aplicación
  syncPolicy:
    automated:
      prune: true  # Elimina recursos cuando se quitan del repositorio
      selfHeal: true  # Reconcilia el estado cuando el clúster difiere de Git
    syncOptions:
    - CreateNamespace=true  # Crea el namespace si no existe