apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lautaro887/musical-disco.git
    targetRevision: HEAD
    path: prometheus-stack
    helm:
      releaseName: prometheus
      valueFiles:
        - values.yaml
      values: |
        # Puedes incluir valores adicionales aquí si lo necesitas
      parameters:
        # Parámetros adicionales para el chart
      chart: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true