apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lautaro887/musical-disco.git
    targetRevision: HEAD
    path: prometheus-stack/test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: test-monitoreo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true